export const colorsBackgrounds =[    
    {
        "id":1,
        "backgroundUrl":"white",
        "color":"rgba(0,0,0,1)"
    },
    {
        "id":2,
        "backgroundUrl":"white",
        "color":"rgba(0,0,0,1)"
    },
    {
        "id":3,
        "backgroundUrl":"white",
        "color":"rgba(0,0,0,1)"
    },
    {
        "id":4,
        "backgroundUrl":"white",
        "color":"rgba(0,0,0,1)"
    },
]